# Generated by Django 5.1.1 on 2024-09-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FormularioEsporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nivel', models.CharField(max_length=50)),
                ('serie', models.CharField(max_length=50)),
                ('idade', models.IntegerField()),
                ('unidade', models.CharField(choices=[('Primavera', 'Magister Primavera'), ('Bela Vista', 'Magister Bela Vista')], max_length=20)),
                ('responsavel', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
                ('atividades', models.ManyToManyField(to='core.atividade')),
            ],
        ),
    ]
